# product_category -> product_sku -> product(product_name, product_category, brand, size, colour, material)
products_list = {
    "පිරිමි ඇඳුම්": {
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_shirt_1",
            "product_name": "කමිසය",
            "brand": "ලුයිස්",
            "size": "කුඩා",
            "colour": "සුදු",
            "material": "කපු",
            "price": 1000,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_shirt_2",
            "product_name": "කමිසය",
            "brand": "ලුයිස්",
            "size": "කුඩා",
            "colour": "සුදු",
            "material": "සේද",
            "price": 1000,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_shirt_3",
            "product_name": "කමිසය",
            "brand": "ලුයිස්",
            "size": "කුඩා",
            "colour": "කළු",
            "material": "කපු",
            "price": 1000,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_shirt_4",
            "product_name": "කමිසය",
            "brand": "ලුයිස්",
            "size": "කුඩා",
            "colour": "කළු",
            "material": "සේද",
            "price": 1000,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_shirt_5",
            "product_name": "කමිසය",
            "brand": "ලුයිස්",
            "size": "කුඩා",
            "colour": "නිල්",
            "material": "කපු",
            "price": 1000,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_shirt_6",
            "product_name": "කමිසය",
            "brand": "ලුයිස්",
            "size": "කුඩා",
            "colour": "නිල්",
            "material": "සේද",
            "price": 1000,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_shirt_7",
            "product_name": "කමිසය",
            "brand": "ලුයිස්",
            "size": "මධ්යම",
            "colour": "සුදු",
            "material": "කපු",
            "price": 2000,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_shirt_8",
            "product_name": "කමිසය",
            "brand": "ලුයිස්",
            "size": "මධ්යම",
            "colour": "සුදු",
            "material": "සේද",
            "price": 2000,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_shirt_9",
            "product_name": "කමිසය",
            "brand": "ලුයිස්",
            "size": "මධ්යම",
            "colour": "කළු",
            "material": "කපු",
            "price": 2000,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_shirt_10",
            "product_name": "කමිසය",
            "brand": "ලුයිස්",
            "size": "මධ්යම",
            "colour": "කළු",
            "material": "සේද",
            "price": 2000,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_shirt_11",
            "product_name": "කමිසය",
            "brand": "ලුයිස්",
            "size": "මධ්යම",
            "colour": "නිල්",
            "material": "කපු",
            "price": 2000,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_shirt_12",
            "product_name": "කමිසය",
            "brand": "ලුයිස්",
            "size": "මධ්යම",
            "colour": "නිල්",
            "material": "සේද",
            "price": 2000,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_shirt_13",
            "product_name": "කමිසය",
            "brand": "ලුයිස්",
            "size": "විශාල",
            "colour": "සුදු",
            "material": "කපු",
            "price": 2500,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_shirt_14",
            "product_name": "කමිසය",
            "brand": "ලුයිස්",
            "size": "විශාල",
            "colour": "සුදු",
            "material": "සේද",
            "price": 2500,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_shirt_15",
            "product_name": "කමිසය",
            "brand": "ලුයිස්",
            "size": "විශාල",
            "colour": "කළු",
            "material": "කපු",
            "price": 2500,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_shirt_16",
            "product_name": "කමිසය",
            "brand": "ලුයිස්",
            "size": "විශාල",
            "colour": "කළු",
            "material": "සේද",
            "price": 2500,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_shirt_17",
            "product_name": "කමිසය",
            "brand": "ලුයිස්",
            "size": "විශාල",
            "colour": "නිල්",
            "material": "කපු",
            "price": 2500,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_shirt_18",
            "product_name": "කමිසය",
            "brand": "ලුයිස්",
            "size": "විශාල",
            "colour": "නිල්",
            "material": "සේද",
            "price": 2500,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_trouser_1",
            "product_name": "කලිසම",
            "brand": "ලුයිස්",
            "size": "කුඩා",
            "colour": "සුදු",
            "material": "කපු",
            "price": 400,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_trouser_2",
            "product_name": "කලිසම",
            "brand": "ලුයිස්",
            "size": "කුඩා",
            "colour": "සුදු",
            "material": "සේද",
            "price": 400,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_trouser_3",
            "product_name": "කලිසම",
            "brand": "ලුයිස්",
            "size": "කුඩා",
            "colour": "කළු",
            "material": "කපු",
            "price": 400,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_trouser_4",
            "product_name": "කලිසම",
            "brand": "ලුයිස්",
            "size": "කුඩා",
            "colour": "කළු",
            "material": "සේද",
            "price": 400,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_trouser_5",
            "product_name": "කලිසම",
            "brand": "ලුයිස්",
            "size": "කුඩා",
            "colour": "නිල්",
            "material": "කපු",
            "price": 400,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_trouser_6",
            "product_name": "කලිසම",
            "brand": "ලුයිස්",
            "size": "කුඩා",
            "colour": "නිල්",
            "material": "සේද",
            "price": 400,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_trouser_7",
            "product_name": "කලිසම",
            "brand": "ලුයිස්",
            "size": "මධ්යම",
            "colour": "සුදු",
            "material": "කපු",
            "price": 600,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_trouser_8",
            "product_name": "කලිසම",
            "brand": "ලුයිස්",
            "size": "මධ්යම",
            "colour": "සුදු",
            "material": "සේද",
            "price": 600,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_trouser_9",
            "product_name": "කලිසම",
            "brand": "ලුයිස්",
            "size": "මධ්යම",
            "colour": "කළු",
            "material": "කපු",
            "price": 600,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_trouser_10",
            "product_name": "කලිසම",
            "brand": "ලුයිස්",
            "size": "මධ්යම",
            "colour": "කළු",
            "material": "සේද",
            "price": 600,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_trouser_11",
            "product_name": "කලිසම",
            "brand": "ලුයිස්",
            "size": "මධ්යම",
            "colour": "නිල්",
            "material": "කපු",
            "price": 600,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_trouser_12",
            "product_name": "කලිසම",
            "brand": "ලුයිස්",
            "size": "මධ්යම",
            "colour": "නිල්",
            "material": "සේද",
            "price": 600,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_trouser_13",
            "product_name": "කලිසම",
            "brand": "ලුයිස්",
            "size": "විශාල",
            "colour": "සුදු",
            "material": "කපු",
            "price": 800,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_trouser_14",
            "product_name": "කලිසම",
            "brand": "ලුයිස්",
            "size": "විශාල",
            "colour": "සුදු",
            "material": "සේද",
            "price": 800,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_trouser_15",
            "product_name": "කලිසම",
            "brand": "ලුයිස්",
            "size": "විශාල",
            "colour": "කළු",
            "material": "කපු",
            "price": 800,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_trouser_16",
            "product_name": "කලිසම",
            "brand": "ලුයිස්",
            "size": "විශාල",
            "colour": "කළු",
            "material": "සේද",
            "price": 800,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_trouser_17",
            "product_name": "කලිසම",
            "brand": "ලුයිස්",
            "size": "විශාල",
            "colour": "නිල්",
            "material": "කපු",
            "price": 800,
        },
        {
            "product_category":"පිරිමි ඇඳුම්",
            "sku": "mens_trouser_18",
            "product_name": "කලිසම",
            "brand": "ලුයිස්",
            "size": "විශාල",
            "colour": "නිල්",
            "material": "සේද",
            "price": 800,
        },
    },
    "කාන්තා ඇඳුම්": {
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_blouse_1",
            "product_name": "බ්ලවුස්",
            "brand": "ප්රාඩා",
            "size": "කුඩා",
            "colour": "සුදු",
            "material": "කපු",
            "price": 1500,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_blouse_2",
            "product_name": "බ්ලවුස්",
            "brand": "ප්රාඩා",
            "size": "කුඩා",
            "colour": "සුදු",
            "material": "සේද",
            "price": 1500,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_blouse_3",
            "product_name": "බ්ලවුස්",
            "brand": "ප්රාඩා",
            "size": "කුඩා",
            "colour": "කළු",
            "material": "කපු",
            "price": 1500,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_blouse_4",
            "product_name": "බ්ලවුස්",
            "brand": "ප්රාඩා",
            "size": "කුඩා",
            "colour": "කළු",
            "material": "සේද",
            "price": 1500,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_blouse_5",
            "product_name": "බ්ලවුස්",
            "brand": "ප්රාඩා",
            "size": "කුඩා",
            "colour": "නිල්",
            "material": "කපු",
            "price": 1500,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_blouse_6",
            "product_name": "බ්ලවුස්",
            "brand": "ප්රාඩා",
            "size": "කුඩා",
            "colour": "නිල්",
            "material": "සේද",
            "price": 1500,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_blouse_7",
            "product_name": "බ්ලවුස්",
            "brand": "ප්රාඩා",
            "size": "මධ්යම",
            "colour": "සුදු",
            "material": "කපු",
            "price": 2000,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_blouse_8",
            "product_name": "බ්ලවුස්",
            "brand": "ප්රාඩා",
            "size": "මධ්යම",
            "colour": "සුදු",
            "material": "සේද",
            "price": 2000,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_blouse_9",
            "product_name": "බ්ලවුස්",
            "brand": "ප්රාඩා",
            "size": "මධ්යම",
            "colour": "කළු",
            "material": "කපු",
            "price": 2000,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_blouse_10",
            "product_name": "බ්ලවුස්",
            "brand": "ප්රාඩා",
            "size": "මධ්යම",
            "colour": "කළු",
            "material": "සේද",
            "price": 2000,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_blouse_11",
            "product_name": "බ්ලවුස්",
            "brand": "ප්රාඩා",
            "size": "මධ්යම",
            "colour": "නිල්",
            "material": "කපු",
            "price": 2000,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_blouse_12",
            "product_name": "බ්ලවුස්",
            "brand": "ප්රාඩා",
            "size": "මධ්යම",
            "colour": "නිල්",
            "material": "සේද",
            "price": 2000,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_blouse_13",
            "product_name": "බ්ලවුස්",
            "brand": "ප්රාඩා",
            "size": "විශාල",
            "colour": "සුදු",
            "material": "කපු",
            "price": 2500,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_blouse_14",
            "product_name": "බ්ලවුස්",
            "brand": "ප්රාඩා",
            "size": "විශාල",
            "colour": "සුදු",
            "material": "සේද",
            "price": 2500,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_blouse_15",
            "product_name": "බ්ලවුස්",
            "brand": "ප්රාඩා",
            "size": "විශාල",
            "colour": "කළු",
            "material": "කපු",
            "price": 2500,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_blouse_16",
            "product_name": "බ්ලවුස්",
            "brand": "ප්රාඩා",
            "size": "විශාල",
            "colour": "කළු",
            "material": "සේද",
            "price": 2500,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_blouse_17",
            "product_name": "බ්ලවුස්",
            "brand": "ප්රාඩා",
            "size": "විශාල",
            "colour": "නිල්",
            "material": "කපු",
            "price": 2500,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_blouse_18",
            "product_name": "බ්ලවුස්",
            "brand": "ප්රාඩා",
            "size": "විශාල",
            "colour": "නිල්",
            "material": "සේද",
            "price": 2500,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_frock_1",
            "product_name": "ගවුම",
            "brand": "ප්රාඩා",
            "size": "කුඩා",
            "colour": "සුදු",
            "material": "කපු",
            "price": 1600,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_frock_2",
            "product_name": "ගවුම",
            "brand": "ප්රාඩා",
            "size": "කුඩා",
            "colour": "සුදු",
            "material": "සේද",
            "price": 1600,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_frock_3",
            "product_name": "ගවුම",
            "brand": "ප්රාඩා",
            "size": "කුඩා",
            "colour": "කළු",
            "material": "කපු",
            "price": 1600,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_frock_4",
            "product_name": "ගවුම",
            "brand": "ප්රාඩා",
            "size": "කුඩා",
            "colour": "කළු",
            "material": "සේද",
            "price": 1600,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_frock_5",
            "product_name": "ගවුම",
            "brand": "ප්රාඩා",
            "size": "කුඩා",
            "colour": "නිල්",
            "material": "කපු",
            "price": 1600,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_frock_6",
            "product_name": "ගවුම",
            "brand": "ප්රාඩා",
            "size": "කුඩා",
            "colour": "නිල්",
            "material": "සේද",
            "price": 1600,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_frock_7",
            "product_name": "ගවුම",
            "brand": "ප්රාඩා",
            "size": "මධ්යම",
            "colour": "සුදු",
            "material": "කපු",
            "price": 1800,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_frock_8",
            "product_name": "ගවුම",
            "brand": "ප්රාඩා",
            "size": "මධ්යම",
            "colour": "සුදු",
            "material": "සේද",
            "price": 1800,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_frock_9",
            "product_name": "ගවුම",
            "brand": "ප්රාඩා",
            "size": "මධ්යම",
            "colour": "කළු",
            "material": "කපු",
            "price": 1800,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_frock_10",
            "product_name": "ගවුම",
            "brand": "ප්රාඩා",
            "size": "මධ්යම",
            "colour": "කළු",
            "material": "සේද",
            "price": 1800,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_frock_11",
            "product_name": "ගවුම",
            "brand": "ප්රාඩා",
            "size": "මධ්යම",
            "colour": "නිල්",
            "material": "කපු",
            "price": 1800,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_frock_12",
            "product_name": "ගවුම",
            "brand": "ප්රාඩා",
            "size": "මධ්යම",
            "colour": "නිල්",
            "material": "සේද",
            "price": 1800,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_frock_13",
            "product_name": "ගවුම",
            "brand": "ප්රාඩා",
            "size": "විශාල",
            "colour": "සුදු",
            "material": "කපු",
            "price": 2000,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_frock_14",
            "product_name": "ගවුම",
            "brand": "ප්රාඩා",
            "size": "විශාල",
            "colour": "සුදු",
            "material": "සේද",
            "price": 2000,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_frock_15",
            "product_name": "ගවුම",
            "brand": "ප්රාඩා",
            "size": "විශාල",
            "colour": "කළු",
            "material": "කපු",
            "price": 2000,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_frock_16",
            "product_name": "ගවුම",
            "brand": "ප්රාඩා",
            "size": "විශාල",
            "colour": "කළු",
            "material": "සේද",
            "price": 2000,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_frock_17",
            "product_name": "ගවුම",
            "brand": "ප්රාඩා",
            "size": "විශාල",
            "colour": "නිල්",
            "material": "කපු",
            "price": 2000,
        },
        {
            "product_category":"කාන්තා ඇඳුම්",
            "sku": "womens_frock_18",
            "product_name": "ගවුම",
            "brand": "ප්රාඩා",
            "size": "විශාල",
            "colour": "නිල්",
            "material": "සේද",
            "price": 2000,
        },
    },
    "ළමා ඇඳුම්": {
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_shirt_1",
            "product_name": "කමිසය",
            "brand": "කිටී",
            "size": "කුඩා",
            "colour": "සුදු",
            "material": "කපු",
            "price": 1000,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_shirt_2",
            "product_name": "කමිසය",
            "brand": "කිටී",
            "size": "කුඩා",
            "colour": "සුදු",
            "material": "සේද",
            "price": 1000,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_shirt_3",
            "product_name": "කමිසය",
            "brand": "කිටී",
            "size": "කුඩා",
            "colour": "කළු",
            "material": "කපු",
            "price": 1000,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_shirt_4",
            "product_name": "කමිසය",
            "brand": "කිටී",
            "size": "කුඩා",
            "colour": "කළු",
            "material": "සේද",
            "price": 1000,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_shirt_5",
            "product_name": "කමිසය",
            "brand": "කිටී",
            "size": "කුඩා",
            "colour": "නිල්",
            "material": "කපු",
            "price": 1000,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_shirt_6",
            "product_name": "කමිසය",
            "brand": "කිටී",
            "size": "කුඩා",
            "colour": "නිල්",
            "material": "සේද",
            "price": 1000,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_shirt_7",
            "product_name": "කමිසය",
            "brand": "කිටී",
            "size": "මධ්යම",
            "colour": "සුදු",
            "material": "කපු",
            "price": 1200,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_shirt_8",
            "product_name": "කමිසය",
            "brand": "කිටී",
            "size": "මධ්යම",
            "colour": "සුදු",
            "material": "සේද",
            "price": 1200,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_shirt_9",
            "product_name": "කමිසය",
            "brand": "කිටී",
            "size": "මධ්යම",
            "colour": "කළු",
            "material": "කපු",
            "price": 1200,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_shirt_10",
            "product_name": "කමිසය",
            "brand": "කිටී",
            "size": "මධ්යම",
            "colour": "කළු",
            "material": "සේද",
            "price": 1200,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_shirt_11",
            "product_name": "කමිසය",
            "brand": "කිටී",
            "size": "මධ්යම",
            "colour": "නිල්",
            "material": "කපු",
            "price": 1200,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_shirt_12",
            "product_name": "කමිසය",
            "brand": "කිටී",
            "size": "මධ්යම",
            "colour": "නිල්",
            "material": "සේද",
            "price": 1200,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_shirt_13",
            "product_name": "කමිසය",
            "brand": "කිටී",
            "size": "විශාල",
            "colour": "සුදු",
            "material": "කපු",
            "price": 1500,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_shirt_14",
            "product_name": "කමිසය",
            "brand": "කිටී",
            "size": "විශාල",
            "colour": "සුදු",
            "material": "සේද",
            "price": 1500,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_shirt_15",
            "product_name": "කමිසය",
            "brand": "කිටී",
            "size": "විශාල",
            "colour": "කළු",
            "material": "කපු",
            "price": 1500,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_shirt_16",
            "product_name": "කමිසය",
            "brand": "කිටී",
            "size": "විශාල",
            "colour": "කළු",
            "material": "සේද",
            "price": 1500,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_shirt_17",
            "product_name": "කමිසය",
            "brand": "කිටී",
            "size": "විශාල",
            "colour": "නිල්",
            "material": "කපු",
            "price": 1500,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_shirt_18",
            "product_name": "කමිසය",
            "brand": "කිටී",
            "size": "විශාල",
            "colour": "නිල්",
            "material": "සේද",
            "price": 1500,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_trouser_1",
            "product_name": "කලිසම",
            "brand": "කිටී",
            "size": "කුඩා",
            "colour": "සුදු",
            "material": "කපු",
            "price": 600,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_trouser_2",
            "product_name": "කලිසම",
            "brand": "කිටී",
            "size": "කුඩා",
            "colour": "සුදු",
            "material": "සේද",
            "price": 600,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_trouser_3",
            "product_name": "කලිසම",
            "brand": "කිටී",
            "size": "කුඩා",
            "colour": "කළු",
            "material": "කපු",
            "price": 600,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_trouser_4",
            "product_name": "කලිසම",
            "brand": "කිටී",
            "size": "කුඩා",
            "colour": "කළු",
            "material": "සේද",
            "price": 600,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_trouser_5",
            "product_name": "කලිසම",
            "brand": "කිටී",
            "size": "කුඩා",
            "colour": "නිල්",
            "material": "කපු",
            "price": 600,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_trouser_6",
            "product_name": "කලිසම",
            "brand": "කිටී",
            "size": "කුඩා",
            "colour": "නිල්",
            "material": "සේද",
            "price": 600,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_trouser_7",
            "product_name": "කලිසම",
            "brand": "කිටී",
            "size": "මධ්යම",
            "colour": "සුදු",
            "material": "කපු",
            "price": 800,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_trouser_8",
            "product_name": "කලිසම",
            "brand": "කිටී",
            "size": "මධ්යම",
            "colour": "සුදු",
            "material": "සේද",
            "price": 800,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_trouser_9",
            "product_name": "කලිසම",
            "brand": "කිටී",
            "size": "මධ්යම",
            "colour": "කළු",
            "material": "කපු",
            "price": 800,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_trouser_10",
            "product_name": "කලිසම",
            "brand": "කිටී",
            "size": "මධ්යම",
            "colour": "කළු",
            "material": "සේද",
            "price": 800,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_trouser_11",
            "product_name": "කලිසම",
            "brand": "කිටී",
            "size": "මධ්යම",
            "colour": "නිල්",
            "material": "කපු",
            "price": 800,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_trouser_12",
            "product_name": "කලිසම",
            "brand": "කිටී",
            "size": "මධ්යම",
            "colour": "නිල්",
            "material": "සේද",
            "price": 800,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_trouser_13",
            "product_name": "කලිසම",
            "brand": "කිටී",
            "size": "විශාල",
            "colour": "සුදු",
            "material": "කපු",
            "price": 1000,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_trouser_14",
            "product_name": "කලිසම",
            "brand": "කිටී",
            "size": "විශාල",
            "colour": "සුදු",
            "material": "සේද",
            "price": 1000,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_trouser_15",
            "product_name": "කලිසම",
            "brand": "කිටී",
            "size": "විශාල",
            "colour": "කළු",
            "material": "කපු",
            "price": 1000,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_trouser_16",
            "product_name": "කලිසම",
            "brand": "කිටී",
            "size": "විශාල",
            "colour": "කළු",
            "material": "සේද",
            "price": 1000,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_trouser_17",
            "product_name": "කලිසම",
            "brand": "කිටී",
            "size": "විශාල",
            "colour": "නිල්",
            "material": "කපු",
            "price": 1000,
        },
        {
            "product_category":"ළමා ඇඳුම්",
            "sku": "kids_trouser_18",
            "product_name": "කලිසම",
            "brand": "කිටී",
            "size": "විශාල",
            "colour": "නිල්",
            "material": "සේද",
            "price": 1000,
        },
    },
    "උපාංග": {
        {
            "product_category":"උපාංග",
            "sku": "shoes_1",
            "product_name": "සපත්තු",
            "brand": "නයික්",
            "size": "කුඩා",
            "colour": "කළු",
            "material": "සම්",
            "price": 100,
        },
        {
            "product_category":"උපාංග",
            "sku": "shoes_2",
            "product_name": "සපත්තු",
            "brand": "නයික්",
            "size": "කුඩා",
            "colour": "කළු",
            "material": "කැන්වස්",
            "price": 100,
        },
        {
            "product_category":"උපාංග",
            "sku": "shoes_1_a",
            "product_name": "සපත්තු",
            "brand": "අඩිඩාස්",
            "size": "කුඩා",
            "colour": "කළු",
            "material": "සම්",
            "price": 100,
        },
        {
            "product_category":"උපාංග",
            "sku": "shoes_2_a",
            "product_name": "සපත්තු",
            "brand": "අඩිඩාස්",
            "size": "කුඩා",
            "colour": "කළු",
            "material": "කැන්වස්",
            "price": 100,
        },
        {
            "product_category":"උපාංග",
            "sku": "shoes_3",
            "product_name": "සපත්තු",
            "brand": "නයික්",
            "size": "මධ්යම",
            "colour": "කළු",
            "material": "සම්",
            "price": 100,
        },
        {
            "product_category":"උපාංග",
            "sku": "shoes_4",
            "product_name": "සපත්තු",
            "brand": "නයික්",
            "size": "මධ්යම",
            "colour": "කළු",
            "material": "කැන්වස්",
            "price": 100,
        },
        {
            "product_category":"උපාංග",
            "sku": "shoes_3_a",
            "product_name": "සපත්තු",
            "brand": "අඩිඩාස්",
            "size": "මධ්යම",
            "colour": "කළු",
            "material": "සම්",
            "price": 100,
        },
        {
            "product_category":"උපාංග",
            "sku": "shoes_4_a",
            "product_name": "සපත්තු",
            "brand": "අඩිඩාස්",
            "size": "මධ්යම",
            "colour": "කළු",
            "material": "කැන්වස්",
            "price": 100,
        },
        {
            "product_category":"උපාංග",
            "sku": "shoes_5",
            "product_name": "සපත්තු",
            "brand": "නයික්",
            "size": "විශාල",
            "colour": "කළු",
            "material": "සම්",
            "price": 100,
        },
        {
            "product_category":"උපාංග",
            "sku": "shoes_6",
            "product_name": "සපත්තු",
            "brand": "නයික්",
            "size": "විශාල",
            "colour": "කළු",
            "material": "කැන්වස්",
            "price": 100,
        },
        {
            "product_category":"උපාංග",
            "sku": "shoes_5_a",
            "product_name": "සපත්තු",
            "brand": "අඩිඩාස්",
            "size": "විශාල",
            "colour": "කළු",
            "material": "සම්",
            "price": 100,
        },
        {
            "product_category":"උපාංග",
            "sku": "shoes_6_a",
            "product_name": "සපත්තු",
            "brand": "අඩිඩාස්",
            "size": "විශාල",
            "colour": "කළු",
            "material": "කැන්වස්",
            "price": 100,
        },
        {
            "product_category":"උපාංග",
            "sku": "socks_1",
            "product_name": "මේස්",
            "brand": "අඩිඩාස්",
            "size": "කුඩා",
            "colour": "කළු",
            "material": "කපු",
            "price": 100,
        },
        {
            "product_category":"උපාංග",
            "sku": "socks_2",
            "product_name": "මේස්",
            "brand": "අඩිඩාස්",
            "size": "කුඩා",
            "colour": "සුදු",
            "material": "කපු",
            "price": 100,
        },
        {
            "product_category":"උපාංග",
            "sku": "socks_3",
            "product_name": "මේස්",
            "brand": "අඩිඩාස්",
            "size": "මධ්යම",
            "colour": "කළු",
            "material": "කපු",
            "price": 100,
        },
        {
            "product_category":"උපාංග",
            "sku": "socks_4",
            "product_name": "මේස්",
            "brand": "අඩිඩාස්",
            "size": "මධ්යම",
            "colour": "සුදු",
            "material": "කපු",
            "price": 100,
        },
        {
            "product_category":"උපාංග",
            "sku": "socks_5",
            "product_name": "මේස්",
            "brand": "අඩිඩාස්",
            "size": "විශාල",
            "colour": "කළු",
            "material": "කපු",
            "price": 100,
        },
        {
            "product_category":"උපාංග",
            "sku": "socks_6",
            "product_name": "මේස්",
            "brand": "අඩිඩාස්",
            "size": "විශාල",
            "colour": "සුදු",
            "material": "කපු",
            "price": 100,
        },
        {
            "product_category":"උපාංග",
            "sku": "belt_1",
            "product_name": "බඳ පටිය",
            "brand": "ලුයිස්",
            "size": "කුඩා",
            "colour": "කළු",
            "material": "සම්",
            "price": 100,
        },
        {
            "product_category":"උපාංග",
            "sku": "belt_2",
            "product_name": "බඳ පටිය",
            "brand": "ලුයිස්",
            "size": "කුඩා",
            "colour": "දුඹුරු",
            "material": "සම්",
            "price": 100,
        },
        {
            "product_category":"උපාංග",
            "sku": "belt_3",
            "product_name": "බඳ පටිය",
            "brand": "ලුයිස්",
            "size": "මධ්යම",
            "colour": "කළු",
            "material": "සම්",
            "price": 100,
        },
        {
            "product_category":"උපාංග",
            "sku": "belt_4",
            "product_name": "බඳ පටිය",
            "brand": "ලුයිස්",
            "size": "මධ්යම",
            "colour": "දුඹුරු",
            "material": "සම්",
            "price": 100,
        },
        {
            "product_category":"උපාංග",
            "sku": "belt_5",
            "product_name": "බඳ පටිය",
            "brand": "ලුයිස්",
            "size": "විශාල",
            "colour": "කළු",
            "material": "සම්",
            "price": 100,
        },
        {
            "product_category":"උපාංග",
            "sku": "belt_6",
            "product_name": "බඳ පටිය",
            "brand": "ලුයිස්",
            "size": "විශාල",
            "colour": "දුඹුරු",
            "material": "සම්",
            "price": 100,
        },
    },
}

# mens - shirt,trousers | white,black,blue| small,medium,large | silk,cotton